# -*- coding: utf-8 -*-

# Two train mode: pretrain / fine_tune
TRAIN_MODE = 'pretrain'

if TRAIN_MODE == 'fine_tune':
    # fine tune on south park persona
    CORPUS_NAME = "persona_data"
    CORPUS_FILE = "train.txt"
    USE_PERSONA = True          # whether to update the persona embedding during training
else:
    # pretrain on cornell movie and south park general
    CORPUS_NAME = "general_data"
    CORPUS_FILE = "train.txt"
    USE_PERSONA = False         # whether to update the persona embedding during training

# checkpoints relevant
SAVE_DIR = 'checkpoints'
MODEL_NAME = 'dwy_persona_based'
N_ITER = 150 * 10 ** 3               # training iterations

# Configure models - chat relevant
BEAM_SEARCH_ON = True       # use Beam Search or Greedy Search
BEAM_WIDTH = 10              # size of beam
BEAM_CANDIDATE_NUM = 3       # number of sentences generated by beam search

# Configure models - training relevant
RNN_TYPE = 'LSTM'            # use LSTM or GRU as RNN
ATTN_MODEL = 'dot'           # type of the attention model: dot/general/concat
TRAIN_EMBEDDING = True       # whether to update the word embeddding during training
HIDDEN_SIZE = 300            # size of the word embedding & number of hidden units in GRU
PERSONA_SIZE = 30           # size of the persona embedding
ENCODER_N_LAYERS = 2         # number of layers in bi-GRU encoder
DECODER_N_LAYERS = 2         # number of layers in GRU decoder
ENCODER_DROPOUT_RATE = 0.1   # dropout rate in bi-GRU encoder
DECODER_DROPOUT_RATE = 0.1   # dropout rate in GRU decoder
TEACHER_FORCING_RATIO = 1.0  # ratio for training decoder on ground truth or last output of decoder

# Configure training/optimization
BATCH_SIZE = 64            # size of the mini batch in training state
CLIP = 50.0                # gradient norm clip
LR = 0.0001                # encoder learning ratio
DECODER_LR = 5.0           # decoder learning ratio: LR*DECODER_LR
PRINT_EVERY = 100          # print the loss every x iterations
SAVE_EVERY = 1000          # save the checkpoint every x iterations
TF_RATE_DECAY_FACTOR = 15 * 10 ** 3      # k in the inverse sigmoid decay func of the teacher force rate k/(k+exp(i/k)), which is related to N_ITER

# Parameters for processing the dataset
MAX_LENGTH = 20  # Maximum sentence length to consider

SPECIAL_WORD_EMBEDDING_TOKENS = {
    'PAD': '<pad>', # Padding token
    'SOS': '<sos>', # Start of Sentence token
    'EOS': '<eos>', # End of Sentence token
    'UNK': '<unk>' # pretrained word embedding usually has this
}

PERSONS = ['kyle', 'cartman', 'stan', 'chef', 'kenny', 'mr. garrison',
           'randy', 'sharon', 'gerald', 'butters']

NONE_PERSONA = '<none>'

# Word Embedding
WORD_EMBEDDING_FILES = [
    'data/word_embedding/filtered.glove.42B.300d.part1.txt',
    'data/word_embedding/filtered.glove.42B.300d.part2.txt'
]
